"""empty message

Revision ID: c661a77612be
Revises: c98207ac7118
Create Date: 2018-05-10 02:38:18.620435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c661a77612be'
down_revision = 'c98207ac7118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_text', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
